print(100)
print(200)
print("Hello World!")
print("Hello World!")
print("Hello World!")
print("Hello World!")
print("Hello World!")
print("Hello World!")

first_number=input("Elso szam?")
print(first_number)
second_number=input("Masodik szam?")
print(second_number)
print(int (first_number) + int(second_number))