# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome("/Users/agnessrancsik/Selenium/Masodikora_1030/tests/chromedriver")
driver.get("http://learnwebservices.com/locations/server")


class TestCreatelocation():
  def setup_method(self, method):
    self.driver = webdriver.Chrome("/Users/agnessrancsik/Selenium/Masodikora_1030/tests/chromedriver")
    self.vars = {}

  def test_createlocation(self):
    self.driver.get("http://www.learnwebservices.com/locations/server")
    self.driver.set_window_size(1226, 731)
    self.driver.find_element(By.ID, "nameInput").click()
    self.driver.find_element(By.ID, "nameInput").send_keys("a")
    self.driver.find_element(By.ID, "coordsInput").send_keys("1,1")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert").text == "Location has saved."